server:
  port: 80
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/contract?useUnicode=true&characterEncoding=UTF-8&useSSL=false&jdbcCompliantTruncation=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: MyNewPass4!
    driver-class-name: com.mysql.jdbc.Driver
    ###################以下为druid增加的配置###########################
    druid:
      # 初始化时建立物理连接的个数
      initial-size: 5
      # 最大连接池数量
      max-active: 30
      # 最小连接池数量
      min-idle: 5
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 300000
      # 用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: SELECT 1 FROM DUAL
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: true
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      max-pool-prepared-statement-per-connection-size: 50
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
    ###############以上为配置druid添加的配置########################################
  resources:
      static-locations: classpath:/static,file:/data/works/upload/
  servlet:
      multipart:
            max-file-size: 100MB
            max-request-size: 100MB

xin:
  uploader:
#用户\合同\附存path路径image\file\attachment\txtfile必保留,/data/works/upload/可以替换
#用户图片文件存储目录
    image-path: /data/works/upload/image
#合同文件存储目录
    common-file-path: /data/works/upload/file
#PDF文件存储目录
    attachment-path: /data/works/upload/attachment
#TXT文件存储目录
    txt-file-path: /data/works/upload/txtfile
#子目录策略，用于减少一个文件夹里的文件数：可选year;month;day;hour
    child-path-strategy: day
#year;month;day;hour
#文件服务器域名
    domain: http://39.96.22.77:80
#静态文件地址,必须与上面static-locations的配置路径相同
    static-file-path: /data/works/upload

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.seven.account.manage.model
  config-location: classpath:/mybatis-config.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  file: logs/ContractManageSite.log
  level:
    root: WARN
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.seven: DEBUG